# Generated by Django 4.0.4 on 2024-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=25, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
